### PR TITLE
python2 to 3 conversion backport to b4.4

### PR DESCRIPTION
**Pull request by jennfshr**
Pulling in the changes to bring python2 to python3 into the b4.4 branch. @baallan

### CODE REVIEW

**Comment by morrone** [comment]
@jennfshr @tom95858 - Please, in the future ensure that backports are strict one-to-one commit backports instead of merging multiple commits together for a port. It is _much_ more difficult to look at the branch histories and see what has been synced if the backported commits don't each appear in the "git log --oneline" log with subject lines that are substantially the same (maybe just a backport note appened to the subject line).

**Comment by jennfshr** [comment]
I created that port by doing a git diff on the changed files from the OVIS-4 branch to the b4.4 branch, then applying the patch to a clone of the b4.4 branch. In hindsight, I should have squashed (I thought I marked it as such w/ my OVIS-4 pull request) the commits for the initial python2->3 port, then a single commit comparison for both branches would have been more straightforward.  I see what you mean and appreciate the constructive feedback.

From: Christopher J. Morrone ***@***.***>
Date: Monday, October 14, 2024 at 4:57 PM
To: ovis-hpc/ldms ***@***.***>
Cc: Green, Jennifer Kathleen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ovis-hpc/ldms] python2 to 3 conversion backport to b4.4 (PR #1451)

@jennfshr<https://github.com/jennfshr> @tom95858<https://github.com/tom95858> - Please, in the future ensure that backports are strict one-to-one commit backports instead of merging multiple commits together for a port. It is much more difficult to look at the branch histories and see what has been synced if the backported commits don't each appear in the "git log --oneline" log with subject lines that are substantially the same (maybe just a backport note appened to the subject line).

**Comment by morrone** [comment]
@jennfshr The best way to do a backport (or forward port) is to start with the "git cherry-pick" command. I think you'll find that makes your life much easier, because you won't need to do all of that manual diff+patching. You can let git do the work (including preserving original commit message and authorship), and just resolve any commit conflicts.

And it does look like something went wrong in this backport, because we are missing at least the ovis-roll-over.py python2->python3 changes.

**Comment by tom95858** [comment]
I can squash it when I accept the pull request. That said, have we confirmed that we need or use any of these scripts? I mean they haven't worked for more than a few years, so why are we maintaining them?

**Comment by jennfshr** [comment]
Ben tested (and fixed) my port of these scripts. I think that revisiting their usefulness is a good idea, as well as further testing/peer review.  I think that we do use some of them (i.e., the ldms_sensors_config script we actively use) @baallan has way more experience than I do on this.  My motivation for updating them was so rpm wasn’t forcing a python2 requirement.

**Comment by baallan** [comment]
@tom95858 yes we have confirmed that we need them. all but the mpi are in routine use; the mpi supports a research plugin with episodic use.

**Pull request merged**
