### PR TITLE
Fix `zap_ugni` bug in endpoint rejection path

### PR DESCRIPTION
**Pull request by narategithub**
This is not tested yet.

### CODE REVIEW

**Comment by tom95858** [comment]
@morrone would it  be possible for you to test this. We have lost access to a uGNI machine.

**Comment by morrone** [comment]
> @morrone would it be possible for you to test this. We have lost access to a uGNI machine.

I don't think that we have uGNI either.

**Comment by tom95858** [comment]
@narategithub please add @bschwal or someone else who has access to uGNI as a reviewer to test this.

**Comment by bschwal** [comment]
Brandt is the only person who really has a knowledge of building and running on cray.

**Comment by tom95858** [comment]
@narategithub Let's confirm that this will never see the light of day and then just close it.

**Pull request closed without merging**
